// Generated by ReScript, PLEASE EDIT WITH CARE

import OtherJsx from "./other.jsx";
import * as JsxRuntime from "react/jsx-runtime";

var make = OtherJsx;

function App(props) {
  return JsxRuntime.jsx("div", {
              children: JsxRuntime.jsx(make, {})
            });
}

var make$1 = App;

export {
  make$1 as make,
}
/* make Not a pure module */
